version: '3.8'

services:
  api:
    container_name: bonbast-api
    build: .
    restart: always
    ports:
      - "5050:5001"
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - API_DB_PATH=/data/api_manager.db
      - API_KEY_PEPPER_PATH=/data/api_key_pepper
      # - ADMIN_TOKEN=change-me
    shm_size: '2gb'
    volumes:
      - ./data:/data

  frontend:
    container_name: bonbast-frontend
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
