name: Deploy to Server

on:
  push:
    branches:
      - main  # هر وقت روی main پوش شد، اجرا بشه

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # رفتن به پوشه پروژه
            cd ~/bonbast-api
            
            # دریافت آخرین تغییرات
            git pull origin main
            
            # پاکسازی کانتینرهای نام‌گذاری‌شده قدیمی (برای جلوگیری از Conflict روی container_name)
            docker rm -f bonbast-api bonbast-frontend 2>/dev/null || true

            # توقف کامل و حذف سرویس‌های قبلی (برای جلوگیری از سرو شدن نسخه قدیمی فرانت)
            docker-compose down --remove-orphans

            # ساخت مجدد و اجرای کانتینرها
            docker-compose up -d --build --force-recreate --remove-orphans
            
            # پاکسازی ایمیج‌های قدیمی برای پر نشدن حافظه سرور
            docker image prune -f
